import {
  Archive,
  ArchiveRestore,
  ArrowDownLeft,
  ArrowLeft,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Bus,
  CalendarDays,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock3,
  Database,
  FileText,
  Home,
  LogIn,
  LogOut,
  Menu,
  Moon,
  PartyPopper,
  Pencil,
  Percent,
  PiggyBank,
  Plus,
  PlusCircle,
  RefreshCw,
  Repeat,
  Save,
  Settings,
  Shield,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tag,
  Trash,
  Trash2,
  Upload,
  User,
  UtensilsCrossed,
  Wallet,
  X
} from 'lucide';

export const icons = {
  Archive,
  ArchiveRestore,
  ArrowDownLeft,
  ArrowLeft,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Bus,
  CalendarDays,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock3,
  Database,
  FileText,
  Home,
  LogIn,
  LogOut,
  Menu,
  Moon,
  PartyPopper,
  Pencil,
  Percent,
  PiggyBank,
  Plus,
  PlusCircle,
  RefreshCw,
  Repeat,
  Save,
  Settings,
  Shield,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tag,
  Trash,
  Trash2,
  Upload,
  User,
  UtensilsCrossed,
  Wallet,
  X,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-down-left': ArrowDownLeft,
  'arrow-left': ArrowLeft,
  'arrow-up-right': ArrowUpRight,
  'bar-chart-3': BarChart3,
  'book-open': BookOpen,
  bus: Bus,
  'calendar-days': CalendarDays,
  'check-circle': CheckCircle,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  'clock-3': Clock3,
  database: Database,
  'file-text': FileText,
  home: Home,
  'log-in': LogIn,
  'log-out': LogOut,
  menu: Menu,
  moon: Moon,
  'party-popper': PartyPopper,
  pencil: Pencil,
  percent: Percent,
  'piggy-bank': PiggyBank,
  plus: Plus,
  'plus-circle': PlusCircle,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  save: Save,
  settings: Settings,
  shield: Shield,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  sun: Sun,
  tag: Tag,
  trash: Trash,
  'trash-2': Trash2,
  upload: Upload,
  user: User,
  'utensils-crossed': UtensilsCrossed,
  wallet: Wallet,
  x: X
};
